export const gameTypes = [
  {
    title: 'Memory game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '20mins',
    descriptions: ['strategic', 'competitive', '2-player'],
  },
  {
    title: 'Bluffing game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '20mins',
    descriptions: ['strategic', 'competitive', '2-player'],
  },
  {
    title: 'Action game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '15mins',
    descriptions: ['fast-paced', 'competitive', 'short', 'simple', '2-player'],
  },
  {
    title: 'Market game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '20mins',
    descriptions: ['strategic', 'competitive', '2-player'],
  },
  {
    title: 'Co-operative game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '20mins',
    descriptions: ['strategic', 'teamwork', '2-player'],
  },
  {
    title: 'Warm Up game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '5-6',
    duration: '2mins',
    descriptions: ['fast-paced', 'simple', '4+ players', 'short'],
  },
  {
    title: 'Tile game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '25mins',
    descriptions: ['strategic', 'competitive', '2-player'],
  },
  {
    title: 'Deduction game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '3-6',
    duration: '10mins',
    descriptions: ['strategic', 'competitive', '4+ players'],
  },
  {
    title: 'Numbers game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '15mins',
    descriptions: ['strategic', 'teamwork', '2-player'],
  },
  {
    title: 'Bidding game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '15mins',
    descriptions: ['strategic', 'competitive', '2-player'],
  },
  {
    title: 'Party game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '3-8',
    duration: '20mins',
    descriptions: [
      '4+ players',
      'words',
      'creative',
      'fast-paced',
      'simple',
      'short'
    ],
  },
  {
    title: 'Storytelling game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-5',
    duration: '10mins',
    descriptions: [
      '2-player',
      '4+ players',
      'words',
      'creative',
      'fast-paced',
      'short'
    ],
  },
  {
    title: 'Dice game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-5',
    duration: '25mins',
    descriptions: [
      'strategic',
      'competitive',
      '2-player',
      '4+ players',
    ],
  },
  {
    title: 'Set collecting game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '15mins',
    descriptions: ['strategic', 'competitive', '2-player'],
  },
  {
    title: 'Hidden Identity game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '4-7',
    duration: '10mins',
    descriptions: [
      'strategic',
      'teamwork',
      '4+ players',
      'fast-paced',
    ],
  },
];
