export const gameTypes = [
  {
    title: 'Memory game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '20mins',
    descriptions: ['strategic', 'competitive', '2-player'],
  },
  {
    title: 'Bluffing game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '20mins',
    descriptions: ['strategic', 'sneaky', 'competitive', '2-player'],
  },
  {
    title: 'Action game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '15mins',
    descriptions: ['fast-paced', 'competitive', 'kids-friendly', '2-player'],
  },
  {
    title: 'Market game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '20mins',
    descriptions: ['strategic', 'competitive', '2-player'],
  },
  {
    title: 'Co-operative game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '20mins',
    descriptions: ['strategic', 'teamwork', '2-player'],
  },
  {
    title: 'Warm Up game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '5-6',
    duration: '2mins',
    descriptions: ['fast-paced', 'kids-friendly', 'more than 4 players'],
  },
  {
    title: 'Tile game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '25mins',
    descriptions: ['strategic', 'competitive', '2-player', 'sneaky'],
  },
  {
    title: 'Deduction game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '3-6',
    duration: '10mins',
    descriptions: ['strategic', 'competitive', 'sneaky', 'more than 4 players'],
  },
  {
    title: 'Numbers game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '15mins',
    descriptions: ['strategic', 'teamwork', '2-player'],
  },
  {
    title: 'Bidding game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '15mins',
    descriptions: ['strategic', 'competitive', '2-player'],
  },
  {
    title: 'Party game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '3-8',
    duration: '20mins',
    descriptions: [
      'non-competitive',
      'more than 4 players',
      'uses words/language',
      'uses imagination',
      'kids-friendly',
      'fast-paced',
    ],
  },
  {
    title: 'Storytelling game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-5',
    duration: '10mins',
    descriptions: [
      'non-competitive',
      '2-player',
      'more than 4 players',
      'uses words/language',
      'uses imagination',
      'kids-friendly',
      'fast-paced',
    ],
  },
  {
    title: 'Dice game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-5',
    duration: '25mins',
    descriptions: [
      'strategic',
      'competitive',
      '2-player',
      'more than 4 players',
    ],
  },
  {
    title: 'Set collecting game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '2-4',
    duration: '15mins',
    descriptions: ['strategic', 'competitive', '2-player'],
  },
  {
    title: 'Hidden Identity game',
    icon: '/images/gameIconPlaceholder.png',
    description: 'Memory game description',
    numberOfPlayers: '4-7',
    duration: '10mins',
    descriptions: [
      'strategic',
      'teamwork',
      'more than 4 players',
      'sneaky',
      'fast-paced',
    ],
  },
];
